version: "3.7"

services:

  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_DATABASE: evolutions_sample
      MYSQL_ROOT_PASSWORD: evolutions_sample
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql:
